import type { Metadata } from "next";
import "./globals.css";
import { Poppins} from "next/font/google";
import Footer from "./component/footer";
import Navbar from "./component/navbar";
import TopHeader from "./component/topHeader";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <TopHeader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
