import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins} from "next/font/google";
import Footer from "./component/footer";
import Navbar from "./component/navbar";
import TopHeader from "./component/topHeader";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
});


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <TopHeader />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
